### DISCUSSION TITLE
Changing the Font Size

### DISCUSSION THREAD

**Discussion by Li-Yuanyuan** [boris-jenicek/ngx-awesome-popup#22] [Features request]
Is it possible to make the font size configurable? Currently, it seems that I have to use both "::ng-deep" and "!important" to change the font size, eg:

```css
  ::ng-deep .text-wrapper {
    font-size: 12px !important;
  }
```
